hw
Chris11m22/c3.w2 pull request #1
Opened 2023-01-19 20:04 UTC by Chris11m22

2023-01-20 06:38 UTC, OlgaLugacheva requested changes

2023-01-20 06:38 UTC, OlgaLugacheva commented on src/main/java/com/example/recipeapp/controllers/IngredientController.java
> +    public String addIngredient(@RequestParam String name, @RequestParam int count, @RequestParam String units) {
вместо RequestParam спользуй RequestBody и Ingredient а не отделдьно по параметрам

2023-01-20 06:38 UTC, OlgaLugacheva commented on src/main/java/com/example/recipeapp/controllers/RecipeController.java
> +    public String addRecipe(@RequestParam String name, @RequestParam int min, @RequestParam List<Ingredients> ingrList, @RequestParam List<String> steps) {
RequestBody и Recipe вместо параметров

2023-01-20 06:38 UTC, OlgaLugacheva commented on src/main/java/com/example/recipeapp/controllers/RecipeController.java
> +    private RecipeServiceImpl recipeService;
инжектить нужно интерфейс

2023-01-20 06:38 UTC, OlgaLugacheva commented on src/main/java/com/example/recipeapp/controllers/IngredientController.java
>      private IngredientServiceImpl ingredientService;
инжектить нужно интерфейс

2023-01-20 06:38 UTC, OlgaLugacheva commented on src/main/java/impl/IngredientServiceImpl.java
> +    public void addIngredient(String nameIngredient, int count, String units) {
сразу передавай сюда Ingredient

2023-01-20 06:38 UTC, OlgaLugacheva commented on src/main/java/impl/RecipeServiceImpl.java
> +        recipeMap.put(id++, new Recipe(nameRecipe, minutes, ingredientsList, steps));
сразу передавай сюда Recipe

2023-01-21 13:42 UTC, OlgaLugacheva approved these changes

2023-01-25 16:40 UTC, OlgaLugacheva requested changes

2023-01-25 16:40 UTC, OlgaLugacheva commented on src/main/java/com/example/recipeapp/controllers/IngredientController.java
> +    public Ingredients getIngredient(@RequestParam int id) {
лучше вместо @RequestParam  использовать PathVariable

2023-01-25 16:40 UTC, OlgaLugacheva commented on src/main/java/com/example/recipeapp/controllers/IngredientController.java
> +    @GetMapping("/get")
в маппинге лучше не писать get. add,  edit, delete 
за что эти эндпоинты отвечают, понятно уже по аннотации

2023-01-25 16:40 UTC, OlgaLugacheva commented on src/main/java/com/example/recipeapp/controllers/IngredientController.java
> +    @DeleteMapping("/delete/{id}")
тут верно, но delete лучше убрать

2023-01-25 16:40 UTC, OlgaLugacheva commented on src/main/java/com/example/recipeapp/controllers/IngredientController.java
> +    public ResponseEntity<Ingredients> editIngredient (@PathVariable int id, @RequestBody Ingredients ingredient) {
тут тоже верно

2023-01-25 16:40 UTC, OlgaLugacheva commented on src/main/java/com/example/recipeapp/controllers/RecipeController.java
> +    @GetMapping("/get")
см комментарии выше

2023-01-28 18:09 UTC, OlgaLugacheva approved these changes

2023-01-29 14:33 UTC, DmitryN10 commented on src/main/java/impl/FileServiceImpl.java
> +    public boolean saveToFile(String json) {
@Override

2023-02-15 06:29 UTC, OlgaLugacheva requested changes

2023-02-15 06:29 UTC, OlgaLugacheva commented on src/main/java/controllers/FilesController.java
> +                IOUtils.copy(file.getInputStream(), fos);
все действия с файлами и потоками данных лучше выносить в сервис

2023-02-15 06:29 UTC, OlgaLugacheva commented on src/main/java/impl/FileServiceImpl.java
> +            throw new RuntimeException(e);
используй свое исключение

2023-02-15 06:29 UTC, OlgaLugacheva commented on src/main/java/impl/FileServiceImpl.java
> +            throw new RuntimeException(e);
здесь и далее вместо runtime - свое исключение

2023-02-15 06:29 UTC, OlgaLugacheva commented on src/main/java/impl/IngredientServiceImpl.java
> +        return null;
вместо null бросай свое исключение

2023-02-16 19:28 UTC, merged